Work with tar and zip archive urls

diff --git a/build-nginx b/build-nginx
--- a/build-nginx
+++ b/build-nginx
@@ -22,10 +22,11 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 # DEALINGS IN THE SOFTWARE.
 #
-# Builds nginx with an optional list of
+# Fetches and builds nginx, plus optional components like openssl, PCRE and any
+# 3rd-party modules you specify.
 #
 # Requires git version 1.7.10 or later (--single-branch option)
-# and wget
+# wget, tar and zip (to expand non-git archive files).
 #
 # Call with ./build-nginx to clone and compile the various modules and
 # nginx itself. Defaults to building in ~/src/nginx-build
@@ -76,19 +77,83 @@ module_configure_dir() {
 }
 
 expand_error() {
-  echo nope $1 && exit 1
+  echo "Couldn't extract $1" && exit 1
 }
 
+# Given an archive file url (e.g. https://github.com/arut/nginx-rtmp-module/archive/master.zip)
+# turn this into a file-system safe filename we can save the archive to,
+# e.g https___github_com_arut_nginx-rtmp-module_archive_master.zip
+url_to_filename() {
+  archive_url="$1"
+  archive_path="$(dirname $archive_url)"
+  archive_path="${archive_path//[.:\/]/_}"
+  archive_file="${archive_path}_$(basename "$archive_url")"
+  echo $archive_file
+}
+
+# Does the archive have a containing folder
+archive_has_containing_folder() {
+  archive_file=$1
+
+  case "$archive_file" in
+    *tar.gz*) (tar -ztf "$archive_file" | head -1 | grep -q \/);;
+    *tgz*)    (tar -ztf "$archive_file" | head -1 | grep -q \/);;
+    *zip)     (zipinfo -Z1 "$archive_file" | head -1 | grep -q \/);;
+  esac && echo $?
+}
+
+# Extract the tar archive $1 to folder $2
+# if it has a containing folder, then strip the initial folder in the archive
+untar_archive() {
+  archive_file="$1"
+  destination="$2"
+  strip_containing_folder=$(archive_has_containing_folder "$1")
+
+  rm -rf "$destination"
+  mkdir -f "$destination"
+  if [ $strip_containing_folder == "0" ]; then
+    tar -xf --strip-components 1 -C "$destination" "$archive_file"
+  else
+    tar -xf -C "$destination" "$archive_file"
+  fi
+}
+
+# Extract the zip archive $1 to folder $2
+# if it has a containing folder, then strip the initial folder in the archive
+unzip_archive() {
+  archive_file="$1"
+  destination="$2"
+
+  # echo archive_file: $archive_file
+  # echo destination: $destination
+
+  strip_containing_folder=$(archive_has_containing_folder "$1")
+
+  # echo "strip_containing_folder? $strip_containing_folder"
+
+  rm -rf "$destination"
+  unzip -u "$archive_file" -d "$destination"
+  if [ "$strip_containing_folder" -eq "0" ]; then
+    mv "$destination"/*/* "$destination"
+  fi
+}
+
+# Fetches the archive url and expands it into a folder
+# named like the url it came from
 download_and_expand() {
   dir="$1"
   archive_url="$2"
-  archive_file="$(basename "$archive_url")"
+  archive_file=$(url_to_filename "$archive_url")
+  archive_extension="${archive_file##*.}"
+  expanded_destination="$(basename $archive_file .$archive_extension)"
+
   wget "$archive_url" -O "$dir/$archive_file"
   case "$archive_url" in
-    *tar.gz*) (cd "$dir" && tar -zxf "$archive_file") || expand_error $archive_url ;;
-    *tgz*)    (cd "$dir" && tar -zxf "$archive_file") || expand_error $archive_url ;;
-    *zip)     (cd "$dir" && unzip -fo "$archive_file") || expand_error $archive_url ;;
+    *tar.gz*) (untar_archive "$dir/$archive_file" "$dir/$expanded_destination") || expand_error $archive_url ;;
+    *tgz*)    (untar_archive "$dir/$archive_file" "$dir/$expanded_destination") || expand_error $archive_url ;;
+    *zip)     (unzip_archive "$dir/$archive_file" "$dir/$expanded_destination") || expand_error $archive_url ;;
   esac
+
 }
 
 clone_error() {
@@ -111,7 +176,7 @@ clone_at_version() {
     # git clone
     cd "$dir"
     rm -rf "$4"
-    git clone "$repo" --branch "$tag" --single-branch  "$4" || clone_error "$repo" "$tag" "$4"
+    git clone --depth 1 "$repo" --branch "$tag" --single-branch  "$4" || clone_error "$repo" "$tag" "$4"
   fi
 }
 
@@ -171,14 +236,14 @@ clone_nginx_and_modules() {
         *tgz*)    extension=".tgz" ;;
         *zip)     extension=".zip" ;;
       esac
-      source_dir="$build_dir/$(basename $repo_url $extension)"
+      add_module_dir="$build_dir/$(basename $(url_to_filename "$repo_url") $extension)"
     else
       branch=${branch:-master}
       source_dir="$build_dir/$(basename $repo_url .git)-$branch"
     fi
 
-    add_module_dir="$source_dir/$add_module_dir"
-    add_module_dir="${add_module_dir%/}" # strip the trailing slash
+    # add_module_dir="$source_dir/$add_module_dir"
+    # add_module_dir="${add_module_dir%/}" # strip the trailing slash
 
     # We don't want add nginx itself (it's always the first element
     # of the sources array)
@@ -312,7 +377,6 @@ if [ -n "${clone_only:-}" ]; then
 fi
 
 # If we're cloning and building, clean, configure and build
-echo cd "$nginx_dir"
 make clean || echo "No Makefile to clean"
 
 # If we cloned from git, we call ./auto/configure but if we
@@ -329,6 +393,5 @@ if [ -n "${nginx_configure_options:-}" ]; then
 else
   cd "$nginx_dir" && $conf $add_module
 fi
-
 make && echo "Built nginx at $nginx_dir/objs/nginx" || echo "Build failed"
 # and we're done
